CREATE TABLE IF NOT EXISTS USERS_ARIASCHORUS (login VARCHAR(64) PRIMARY KEY,passwd VARCHAR(64));
CREATE TABLE IF NOT EXISTS USER_ROLES_ARIASCHORUS(login VARCHAR(64), role VARCHAR(32));
DELETE from USER_ROLES_ARIASCHORUS;
DELETE from USERS_ARIASCHORUS;
INSERT into USERS_ARIASCHORUS values('admin', 'admin');
INSERT into USERS_ARIASCHORUS values('admin2', 'admin');
INSERT into USER_ROLES_ARIASCHORUS values('admin', 'Manager');
INSERT into USER_ROLES_ARIASCHORUS values('admin2', 'Organizer');
